ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ninos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.registros DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes DISABLE ROW LEVEL SECURITY;
